"""Add First/Last name to User Model

Revision ID: 95715640c775
Revises: 
Create Date: 2023-03-31 10:28:25.490104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95715640c775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='plannerapp_dev'
    )
    with op.batch_alter_table('users', schema='plannerapp_dev') as batch_op:
        batch_op.create_index(batch_op.f('ix_plannerapp_dev_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plannerapp_dev_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_plannerapp_dev_users_username'), ['username'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['plannerapp_dev.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='plannerapp_dev'
    )
    with op.batch_alter_table('books', schema='plannerapp_dev') as batch_op:
        batch_op.create_index(batch_op.f('ix_plannerapp_dev_books_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema='plannerapp_dev') as batch_op:
        batch_op.drop_index(batch_op.f('ix_plannerapp_dev_books_title'))

    op.drop_table('books', schema='plannerapp_dev')
    with op.batch_alter_table('users', schema='plannerapp_dev') as batch_op:
        batch_op.drop_index(batch_op.f('ix_plannerapp_dev_users_username'))
        batch_op.drop_index(batch_op.f('ix_plannerapp_dev_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_plannerapp_dev_users_first_name'))

    op.drop_table('users', schema='plannerapp_dev')
    # ### end Alembic commands ###
